version: "2"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python app.py
    volumes:
      - .:/code
    links:
      - redis
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: .
      dockerfile: DockerfileWorker
    command: rq worker -c rqsettings
    volumes:
      - .:/code
    links:
      - redis
    networks:
      - back-tier

  redis:
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - back-tier

volumes:
  redis-data:
    driver: local

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge